# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guidemo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GuiDemo(object):
    def setupUi(self, GuiDemo):
        GuiDemo.setObjectName("GuiDemo")
        GuiDemo.resize(663, 335)
        self.centralwidget = QtWidgets.QWidget(GuiDemo)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btLoad = QtWidgets.QPushButton(self.widget)
        self.btLoad.setObjectName("btLoad")
        self.horizontalLayout.addWidget(self.btLoad)
        self.leLoad = QtWidgets.QLineEdit(self.widget)
        self.leLoad.setObjectName("leLoad")
        self.horizontalLayout.addWidget(self.leLoad)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btDestroy = QtWidgets.QPushButton(self.widget)
        self.btDestroy.setObjectName("btDestroy")
        self.horizontalLayout_2.addWidget(self.btDestroy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cbGoats = QtWidgets.QCheckBox(self.widget)
        self.cbGoats.setObjectName("cbGoats")
        self.verticalLayout_2.addWidget(self.cbGoats)
        self.cbWombats = QtWidgets.QCheckBox(self.widget)
        self.cbWombats.setObjectName("cbWombats")
        self.verticalLayout_2.addWidget(self.cbWombats)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        GuiDemo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GuiDemo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 663, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setSeparatorsCollapsible(True)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuOther = QtWidgets.QMenu(self.menubar)
        self.menuOther.setObjectName("menuOther")
        GuiDemo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GuiDemo)
        self.statusbar.setObjectName("statusbar")
        GuiDemo.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuOther.menuAction())

        self.retranslateUi(GuiDemo)
        QtCore.QMetaObject.connectSlotsByName(GuiDemo)

    def retranslateUi(self, GuiDemo):
        _translate = QtCore.QCoreApplication.translate
        GuiDemo.setWindowTitle(_translate("GuiDemo", "MainWindow"))
        self.btLoad.setText(_translate("GuiDemo", "Load"))
        self.btDestroy.setText(_translate("GuiDemo", "Destroy"))
        self.cbGoats.setText(_translate("GuiDemo", "Goats"))
        self.cbWombats.setText(_translate("GuiDemo", "Wombats"))
        self.menuFile.setTitle(_translate("GuiDemo", "File"))
        self.menuEdit.setTitle(_translate("GuiDemo", "Edit"))
        self.menuView.setTitle(_translate("GuiDemo", "View"))
        self.menuOther.setTitle(_translate("GuiDemo", "Other"))
